### ISSUE TITLE
php index.php

### ISSUE THREAD

**Issue by BranchScope** [MohsenJS/MadelineprotoPluginSystem#1]
**php index.php**
``PHP Warning:  require(/root/MadelineprotoPluginSystem/vendor/autoload.php): failed to open stream: No such file or directory in /root/MadelineprotoPluginSystem/index.php on line 10
PHP Fatal error:  require(): Failed opening required '/root/MadelineprotoPluginSystem/vendor/autoload.php' (include_path='.:/usr/share/php') in /root/MadelineprotoPluginSystem/index.php on line 10``

**Comment by MohsenJS** [comment]
in the main directory of project run `composer update`
